/**
 * MyTeslaTheater - Card Data Module
 * Contains default card data for popular streaming services
 */

// Define defaultCardData as a window property to avoid duplicate declarations
window.defaultCardData = [
  {
    id: 'netflix',
    title: 'Netflix',
    description: 'Movies, TV shows, and originals',
    url: 'https://www.netflix.com/browse',
    logoUrl: 'assets/logos/netflix.svg',
    brandColor: '#E50914',
    category: 'paid',
    country: 'intl',
    order: 10
  },
  {
    id: 'youtube',
    title: 'YouTube',
    description: 'Videos, shorts, and live streams',
    url: 'https://www.youtube.com/',
    logoUrl: 'assets/logos/youtube.svg',
    brandColor: '#FF0000',
    category: 'free',
    country: 'intl',
    order: 20
  },
  {
    id: 'prime-video',
    title: 'Prime Video',
    description: 'Movies, TV shows, and Amazon Originals',
    url: 'https://www.primevideo.com',
    logoUrl: 'assets/logos/prime-video.svg',
    brandColor: '#00A8E1',
    category: 'paid',
    country: 'intl',
    order: 30
  },
  {
    id: 'disney-plus',
    title: 'Disney+',
    description: 'Disney, Pixar, Marvel, Star Wars, and more',
    url: 'https://www.disneyplus.com/',
    logoUrl: 'assets/logos/disney-plus.svg',
    brandColor: '#0063E5',
    category: 'paid',
    country: 'intl',
    order: 40
  },
  {
    id: 'hulu',
    title: 'Hulu',
    description: 'TV shows, movies, and originals',
    url: 'https://www.hulu.com/',
    logoUrl: 'assets/logos/hulu.svg',
    brandColor: '#1CE783',
    category: 'paid',
    country: 'intl',
    order: 50
  },
  {
    id: 'max',
    title: 'Max',
    description: 'HBO, Max Originals, movies, and more',
    url: 'https://www.max.com/',
    logoUrl: 'assets/logos/max.svg',
    brandColor: '#01A6F1',
    category: 'paid',
    country: 'intl',
    order: 60
  },
  {
    id: 'paramount-plus',
    title: 'Paramount+',
    description: 'Movies, shows, and live sports',
    url: 'https://www.paramountplus.com/',
    logoUrl: 'assets/logos/paramount-plus.svg',
    brandColor: '#0064FF',
    category: 'paid',
    country: 'intl',
    order: 70
  },
  {
    id: 'peacock',
    title: 'Peacock',
    description: 'NBC shows, movies, and originals',
    url: 'https://www.peacocktv.com/',
    logoUrl: 'assets/logos/peacock.svg',
    brandColor: '#000000',
    category: 'paid',
    country: 'intl',
    order: 80
  },
  {
    id: 'apple-tv',
    title: 'Apple TV+',
    description: 'Original shows and movies',
    url: 'https://tv.apple.com/',
    logoUrl: 'assets/logos/apple-tv.svg',
    brandColor: '#000000',
    category: 'paid',
    country: 'intl',
    order: 90
  },
  {
    id: 'twitch',
    title: 'Twitch',
    description: 'Live gaming streams',
    url: 'https://www.twitch.tv/',
    logoUrl: 'assets/logos/twitch.svg',
    brandColor: '#9146FF',
    category: 'free',
    country: 'intl',
    order: 100
  },
  {
    id: 'tubi',
    title: 'Tubi',
    description: 'Free movies and TV shows',
    url: 'https://tubitv.com/',
    logoUrl: 'assets/logos/tubi.svg',
    brandColor: '#FF501A',
    category: 'free',
    country: 'intl',
    order: 110
  },
  {
    id: 'crunchyroll',
    title: 'Crunchyroll',
    description: 'Anime and manga',
    url: 'https://www.crunchyroll.com/',
    logoUrl: 'assets/logos/crunchyroll.svg',
    brandColor: '#F47521',
    category: 'paid',
    country: 'intl',
    order: 120
  },
  {
    id: 'plex',
    title: 'Plex',
    description: 'Your media, plus free movies and TV',
    url: 'https://app.plex.tv/',
    logoUrl: 'assets/logos/plex.svg',
    brandColor: '#E5A00D',
    category: 'free',
    country: 'intl',
    order: 130
  },
  {
    id: 'youtube-tv',
    title: 'YouTube TV',
    description: 'Live TV streaming',
    url: 'https://tv.youtube.com/',
    logoUrl: 'assets/logos/youtube-tv.svg',
    brandColor: '#FF0000',
    category: 'paid',
    country: 'intl',
    order: 140
  },
  {
    id: 'roku',
    title: 'Roku Channel',
    description: 'Free movies and TV',
    url: 'https://therokuchannel.roku.com/',
    logoUrl: 'assets/logos/roku.svg',
    brandColor: '#662D91',
    category: 'free',
    country: 'us',
    order: 160
  },
  {
    id: 'starz',
    title: 'STARZ',
    description: 'Original series and movies',
    url: 'https://www.starz.com/',
    logoUrl: 'assets/logos/starz.svg',
    brandColor: '#000000',
    category: 'paid',
    country: 'intl',
    order: 170
  },
  {
    id: 'facebook',
    title: 'Facebook',
    description: 'Social media and video content',
    url: 'https://www.facebook.com/watch/',
    logoUrl: 'assets/logos/facebook.svg',
    brandColor: '#1877F2',
    category: 'social',
    country: 'intl',
    order: 180
  },
  {
    id: 'twitter',
    title: 'Twitter',
    description: 'News and trending content',
    url: 'https://twitter.com/',
    logoUrl: 'assets/logos/x-twitter.svg',
    brandColor: '#000000',
    category: 'social',
    country: 'intl',
    order: 190
  },
  {
    id: 'joyn',
    title: 'Joyn',
    description: 'German streaming service',
    url: 'https://www.joyn.de/',
    logoUrl: 'assets/logos/joyn.svg',
    brandColor: '#000000',
    category: 'free',
    country: 'de',
    order: 200
  },
  {
    id: 'zdf',
    title: 'ZDF',
    description: 'German public television',
    url: 'https://www.zdf.de/',
    logoUrl: 'assets/logos/zdf.svg',
    brandColor: '#FA7D19',
    category: 'free',
    country: 'de',
    order: 210
  },
  {
    id: 'movistar',
    title: 'Movistar Plus+',
    description: 'Spanish TV and streaming',
    url: 'https://www.movistarplus.es/',
    logoUrl: 'assets/logos/movistar-plus.svg',
    brandColor: '#019DF4',
    category: 'paid',
    country: 'es',
    order: 220
  },
  {
    id: 'filmin',
    title: 'Filmin',
    description: 'Spanish indie films',
    url: 'https://www.filmin.es/',
    logoUrl: 'assets/logos/filmin.svg',
    brandColor: '#00B2E3',
    category: 'paid',
    country: 'es',
    order: 230
  },
  {
    id: 'canal-plus',
    title: 'Canal+',
    description: 'French TV and streaming',
    url: 'https://www.canalplus.com/',
    logoUrl: 'assets/logos/canal-plus.svg',
    brandColor: '#000000',
    category: 'paid',
    country: 'fr',
    order: 240
  },
  {
    id: 'molotov',
    title: 'Molotov TV',
    description: 'French TV streaming',
    url: 'https://www.molotov.tv/',
    logoUrl: 'assets/logos/molotov.svg',
    brandColor: '#F8B747',
    category: 'free',
    country: 'fr',
    order: 250
  },
  {
    id: 'la7',
    title: 'LA7',
    description: 'Italian TV network',
    url: 'https://www.la7.it/tgla7',
    logoUrl: 'assets/logos/la7.svg',
    brandColor: '#BCBEC0',
    category: 'free',
    country: 'it',
    order: 260
  },
  {
    id: 'france24',
    title: 'France 24',
    description: 'International news from France',
    url: 'https://www.france24.com/en/live',
    logoUrl: 'assets/logos/france24.png',
    brandColor: '#0065A3',
    category: 'free',
    country: 'fr',
    order: 270
  },
  {
    id: 'euronews',
    title: 'Euronews',
    description: 'European news channel',
    url: 'https://www.euronews.com/',
    logoUrl: 'assets/logos/euronews.svg',
    brandColor: '#FFFFFF',
    category: 'free',
    country: 'intl',
    order: 280
  },
  {
    id: 'dw',
    title: 'DW',
    description: 'German international broadcaster',
    url: 'https://www.dw.com/en/tv/s-1452',
    logoUrl: 'assets/logos/dw.svg',
    brandColor: '#0098FF',
    category: 'free',
    country: 'de',
    order: 290
  },
  {
    id: 'pluto-tv',
    title: 'Pluto TV',
    description: 'Live TV and on-demand content across various genres',
    url: 'https://pluto.tv/',
    logoUrl: 'assets/logos/pluto-tv.svg',
    brandColor: '#FFFF00',
    category: 'free',
    country: 'intl',
    order: 300
  },
  {
    id: 'sling-tv',
    title: 'Sling TV',
    description: 'Live TV streaming with customizable channel packages',
    url: 'https://www.sling.com/',
    logoUrl: 'assets/logos/sling-tv.svg',
    brandColor: '#0073CD',
    category: 'paid',
    country: 'us',
    order: 310
  },
  {
    id: 'espn-plus',
    title: 'ESPN+',
    description: 'Sports streaming service with live events',
    url: 'https://plus.espn.com/',
    logoUrl: 'assets/logos/espn-plus.svg',
    brandColor: '#FF0000',
    category: 'paid',
    country: 'us',
    order: 320
  },
  {
    id: 'redbull-tv',
    title: 'Red Bull TV',
    description: 'Live events and shows on sports, music, and lifestyle',
    url: 'https://www.redbull.com/',
    logoUrl: 'assets/logos/red-bull-tv.svg',
    brandColor: '#DB0A40',
    category: 'free',
    country: 'intl',
    order: 325
  },
  {
    id: 'fubo-tv',
    title: 'FuboTV',
    description: 'Live sports, TV shows, and movies',
    url: 'https://www.fubo.tv/',
    logoUrl: 'assets/logos/fubo-tv.svg',
    brandColor: '#D4000F',
    category: 'paid',
    country: 'us',
    order: 330
  },
  {
    id: 'discovery-plus',
    title: 'Discovery+',
    description: 'Documentaries and reality TV',
    url: 'https://www.discoveryplus.com/',
    logoUrl: 'assets/logos/discovery-plus.svg',
    brandColor: '#0A66C2',
    category: 'paid',
    country: 'us',
    order: 340
  },
  {
    id: 'curiosity-stream',
    title: 'Curiosity Stream',
    description: 'Documentary streaming service',
    url: 'https://curiositystream.com/',
    logoUrl: 'assets/logos/curiosity-stream.svg',
    brandColor: '#00BFFF',
    category: 'paid',
    country: 'us',
    order: 350
  },
  {
    id: 'crackle',
    title: 'Crackle',
    description: 'Ad-supported movies and TV shows',
    url: 'https://www.crackle.com/',
    logoUrl: 'assets/logos/crackle.svg',
    brandColor: '#FF7500',
    category: 'free',
    country: 'us',
    order: 360
  },
  {
    id: 'popcornflix',
    title: 'Popcornflix',
    description: 'Free movies and webisodes',
    url: 'https://www.popcornflix.com/',
    logoUrl: 'assets/logos/popcornflix.png',
    brandColor: '#FEDA33',
    category: 'free',
    country: 'us',
    order: 370
  },
  {
    id: 'vudu',
    title: 'Vudu',
    description: 'Ad-supported movies and TV shows',
    url: 'https://www.vudu.com/',
    logoUrl: 'assets/logos/vudu.svg',
    brandColor: '#3399FF',
    category: 'free',
    country: 'us',
    order: 380
  },
  {
    id: 'bbc-iplayer',
    title: 'BBC iPlayer',
    description: 'Live and on-demand BBC content',
    url: 'https://www.bbc.co.uk/iplayer',
    logoUrl: 'assets/logos/bbc-iPlayer.svg',
    brandColor: '#FF0000',
    category: 'free',
    country: 'gb',
    order: 390
  },
  {
    id: 'itvx',
    title: 'ITVX',
    description: 'ITV\'s streaming platform',
    url: 'https://www.itv.com/',
    logoUrl: 'assets/logos/itvx.svg',
    brandColor: '#4CABE4',
    category: 'free',
    country: 'gb',
    order: 400
  },
  {
    id: 'all4',
    title: 'All 4',
    description: 'Channel 4\'s on-demand service',
    url: 'https://www.channel4.com/',
    logoUrl: 'assets/logos/all-4.svg',
    brandColor: '#EC008C',
    category: 'free',
    country: 'gb',
    order: 410
  },
  {
    id: 'my5',
    title: 'My5',
    description: 'Channel 5\'s catch-up service',
    url: 'https://www.my5.tv/',
    logoUrl: 'assets/logos/my5.svg',
    brandColor: '#0A0A36',
    category: 'free',
    country: 'gb',
    order: 420
  },
  {
    id: 'britbox',
    title: 'BritBox',
    description: 'British TV boxsets and original series',
    url: 'https://www.britbox.com/',
    logoUrl: 'assets/logos/britbox.svg',
    brandColor: '#C33764',
    category: 'paid',
    country: 'gb',
    order: 430
  },
  {
    id: 'now-tv',
    title: 'Now TV',
    description: 'Sky\'s streaming service',
    url: 'https://www.nowtv.com/',
    logoUrl: 'assets/logos/now-tv.svg',
    brandColor: '#00C800',
    category: 'paid',
    country: 'gb',
    order: 440
  },
  {
    id: 'arte-tv',
    title: 'Arte.tv',
    description: 'Cultural programming and documentaries',
    url: 'https://www.arte.tv/',
    logoUrl: 'assets/logos/arte-tv.svg',
    brandColor: '#FF0000',
    category: 'free',
    country: 'fr',
    order: 450
  },
  {
    id: 'salto',
    title: 'Salto',
    description: 'Joint venture offering French TV content',
    url: 'https://www.salto.fr/',
    logoUrl: 'assets/logos/salto.png',
    brandColor: '#0096FF',
    category: 'paid',
    country: 'fr',
    order: 460
  },
  {
    id: 'magenta-tv',
    title: 'MagentaTV',
    description: 'Telekom\'s streaming service',
    url: 'https://www.magenta.tv/',
    logoUrl: 'assets/logos/magenta-tv.svg',
    brandColor: '#E20074',
    category: 'paid',
    country: 'de',
    order: 470
  },
  {
    id: 'infinity-plus',
    title: 'Infinity+',
    description: 'Mediaset\'s streaming service',
    url: 'https://www.infinityplus.it/',
    logoUrl: 'assets/logos/infinity-plus.svg',
    brandColor: '#00ACEA',
    category: 'paid',
    country: 'it',
    order: 480
  },
  {
    id: 'timvision',
    title: 'TimVision',
    description: 'Telecom Italia\'s platform',
    url: 'https://www.timvision.it/',
    logoUrl: 'assets/logos/timvision.svg',
    brandColor: '#003399',
    category: 'paid',
    country: 'it',
    order: 490
  },
  {
    id: 'videoland',
    title: 'Videoland',
    description: 'RTL\'s streaming service',
    url: 'https://www.videoland.com/',
    logoUrl: 'assets/logos/videoland.png',
    brandColor: '#FF0000',
    category: 'paid',
    country: 'nl',
    order: 500
  },
  {
    id: 'viaplay',
    title: 'Viaplay',
    description: 'Nordic entertainment with sports, movies, and series',
    url: 'https://viaplay.com/',
    logoUrl: 'assets/logos/viaplay.png',
    brandColor: '#E5006B',
    category: 'paid',
    country: 'nordic',
    order: 510
  }
];